### ISSUE TITLE
SimpleDoublePresent Test schlägt fehl

### ISSUE THREAD

**Issue by patricksadowski** [maxraab/Args#3]
`DoubleArgumentMarshaler` nutzt zur Umwandlung eines Textes `CultureInfo.InvariantCulture`. Daher kann nur ein Text mit Punkt als Dezimaltrennzeichen verwendet werden.

Expected: 42,3
Actual:   423

**Comment by maxraab** [comment]
Das klingt sinnvoll und sollte geändert werden.

**Comment by patricksadowski** [comment]
Wir sollten bei der invarianten Kultur bleiben. Soweit mir bekannt, werden Kommandozeilenparameter generell kulturunabhängig angegeben um Scripte nicht anpassen zu müssen.
